# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

def updateProjectBuildNumber

	currentTime = Time.new.strftime("%Y%m%d")
	build = get_build_number()
	if build.include?"#{currentTime}."
	# => 为当天版本 计算迭代版本号
	lastStr = build[build.length-2..build.length-1]
	lastNum = lastStr.to_i
	lastNum = lastNum + 1
	lastStr = lastNum.to_s
	if lastNum < 10
	lastStr = lastStr.insert(0,"0")
	end
	build = "#{currentTime}.#{lastStr}"
	else
	# => 非当天版本 build 号重置
	build = "#{currentTime}.01"
	end
	puts("*************| 更新build #{build} |*************")
	# => 更改项目 build 号
	increment_build_number(
	build_number: "#{build}"
	)
end

#指定项目的scheme名称
scheme=“TestDemo”
#蒲公英api_key和user_key
api_key=“0fb9ad652d4cf6aa433c326ae8a0e3c2”
user_key=“d072cc1fa04658a4da471a7e8099dab0”

platform :ios do

	lane :development_build do|options|
	branch = options[:branch]

	puts “开始打development ipa”

	updateProjectBuildNumber #更改项目build号

	# 开始打包
	gym(
	#输出的ipa名称
	output_name:”#{scheme}_#{get_build_number()}”,
	# 是否清空以前的编译信息 true：是
	clean:true,
	# 指定打包方式，Release 或者 Debug
	configuration:"Release",
	# 指定打包所使用的输出方式，目前支持app-store, package, ad-hoc, enterprise, development
	export_method:"development",
	# 指定输出文件夹
	output_directory:"./fastlane/build",
	)

	puts "开始上传蒲公英"
	# 开始上传蒲公英
	pgyer(api_key: “#{api_key}”, user_key: “#{user_key}”)

	end

  
end
